--- a/package/luci-app-airoha-npu/Makefile
+++ b/package/luci-app-airoha-npu/Makefile
@@ -3,7 +3,7 @@
 include $(TOPDIR)/rules.mk
 
 PKG_VERSION:=1.0.3
-PKG_RELEASE:=1
+PKG_RELEASE:=2
 PKG_LICENSE:=Apache-2.0
 
 LUCI_TITLE:=LuCI Airoha SoC Status (NPU, CPU, Frame Engine)
